Sarona/ViewModels/RedFolderViewModel.cs
using Sarona.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Sarona.ViewModels
{
    public class RedFolderViewModel
    {
        public IEnumerable<PRA_SIP_Sarona> Records { get; set; }
        public string Abb { get; set; }
        public string Code { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public QueryMode Mode { get; set; }
    }
}

Sarona/Controllers/NumberingController.cs
using Microsoft.AspNetCore.Mvc;
using Sarona.Models;
using Sarona.ViewModels;
using System.Collections.Generic;
using System.Linq;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Sarona.Controllers
{
    public class NumberingController : Controller
    {
        private SaronaRepository repository;
        public NumberingController(SaronaRepository rep)
        {
            repository = rep;
        }
        public IActionResult Pool(string prefix = "", int page = 1)
        {
            if (string.IsNullOrEmpty(prefix))
            {
                prefix = "";
            }

            var model = new NumberingPoolViewModel()
            {
                Prefix = prefix,
                Miscs = repository.Miscs.OrderBy(x => x.Name).ToArray(),
                PagingInfo = new PagingInfo()
                {
                    CurrentPage = page,
                    ItemsPerPage = Settings.PageSize,
                    From = (page - 1) * Settings.PageSize,
                    To = (page - 1) * Settings.PageSize + Settings.PageSize,
                    TotalItems = repository.NumberingPools
                                .Where(x => x.Prefix.StartsWith(prefix))
                                .Count()
                },
                Prefixes = repository.GetNps()
                            .Where(x => x.Prefix.StartsWith(prefix))
                            .Skip((page - 1) * Settings.PageSize)
                            .Take(Settings.PageSize)
                            .ToArray()
            };
            return View("Pool", model);
        }

        [HttpPost]
        public IActionResult InsertFreeCodes([Bind(Prefix = nameof(NumberingPoolViewModel.FreeCode))]InsertNumberingPool freeCode, string prefix, int page)
        {
            if (ModelState.IsValid)
            {
                if (repository.InsertFreeCodes(freeCode, User.Identity.Name, out string error, out int addNo))
                {
                    TempData["message"] = $"\"{freeCode.From}\" to \"{freeCode.To}\" ({addNo}) added successfully.";
                    return RedirectToAction(nameof(Pool), new { prefix, page });
                }
                ModelState.AddModelError("overlap", error);
            }

            return Pool(prefix, page);
        }

        public NumberingPool Prefix(long id)
        {
            return repository.NumberingPools.Where(x => x.Id == id).First();
        }

        [HttpPost]
        public IActionResult DeletePrefix(string selectedPrefix, string prefix, int page)
        {
            if (ModelState.IsValid)
            {
                var prefixes = selectedPrefix.Split(',');
                repository.DeleteNumberingPool(prefixes);
                TempData["message"] = $"{string.Join(',',prefixes)} deleted successfully.";
                return RedirectToAction(nameof(Pool), new { prefix });
            }
            return Pool(prefix);
        }

        [HttpPost]
        public IActionResult EditPrefix([Bind(Prefix = nameof(NumberingPoolViewModel.EditPrefix))]NumberingPool editPrefix, string prefix, int page)
        {
            if (ModelState.IsValid)
            {
                editPrefix.Username = User.Identity.Name;
                repository.EditNumberingPool(editPrefix);
                TempData["message"] = $"{editPrefix.Prefix} edited successfully.";
                return RedirectToAction(nameof(Pool), new { prefix });
            }
            return Pool(prefix);
        }

        [HttpPost]
        public IActionResult AddPrefix([Bind(Prefix = nameof(NumberingPoolViewModel.NewPrefix))]NumberingPool np, bool isReservedPrefix, string prefix, int page)
        {
            if (ModelState.IsValid)
            {
                np.Username = User.Identity.Name;
                repository.AddNumberingPool(np, isReservedPrefix);
                TempData["message"] = $"{np.Prefix} added successfully.";
                return RedirectToAction(nameof(Pool), new { np.Prefix });
            }
            return Pool(prefix, page);
        }

        public IActionResult PrefixValidation(string prefix, string oldPrefix)
        {
            var q = repository.PrefixValidationSearch(prefix);
            if(!string.IsNullOrEmpty(oldPrefix))
            {
                if (oldPrefix.StartsWith(prefix) || prefix.StartsWith(oldPrefix))
                    return Json(q.Count() - 1);
            }
            return Json(q.LongCount());
        }




        public IEnumerable<NumberingPool> GetPrefixes(string prefix)
        {
            var q = repository.NumberingPools
                .Where(x => x.Prefix.StartsWith(prefix) && ((x.Status == NumberingStatus.Free || x.Status == NumberingStatus.Reserved) || x.IsFloat))
                .OrderBy(x => x.Prefix).ToArray();
            return q;
        }

        [HttpPost]
        public IActionResult ReserveCodes(Area? area, LinkType? link, string[] prefixes, byte min, byte max, bool changeMinMax)
        {
            if (ModelState.IsValid)
            {
                repository.ReserveCodes(prefixes, area, link, min, max,changeMinMax, User.Identity.Name);
                return Json(true);
            }
            return BadRequest();
        }

        public IActionResult GetSubscribers(string name)
        {
            name = name.Replace('ي', 'ی').Replace('ك', 'ک');
            var subs = repository.NumberingPools.Where(x => x.NormalizedSubscriberName.Contains(name.Replace(" ",""))).Select(x => new { x.Id, x.SubscriberName, x.Abb }).OrderBy(x => x.SubscriberName).GroupBy(x => new { x.SubscriberName, x.Abb }).Select(x => x.First()).ToList();
            return Json(subs);
        }
        [HttpPost]
        public IActionResult AssignPrefix(string selectedPrefix, long customerId, string prefix, int page, LinkType link, LinkDirection direction)
        {
            if (ModelState.IsValid)
            {
                var prefixes = selectedPrefix.Split(',');
                repository.AssignPrefix(prefixes, customerId, User.Identity.Name, link, direction);
                return RedirectToAction(nameof(Pool), new { prefix, page });
            }
            return BadRequest();
        }
        [HttpPost]
        public IActionResult AssignPrefixWithNewCustomer(string selectedPrefix, string abb, string name, string prefix, int page, LinkType link, LinkDirection direction)
        {
            if (ModelState.IsValid)
            {
                var prefixes = selectedPrefix.Split(',');
                repository.AssignPrefix(prefixes, abb, name, User.Identity.Name, link, direction);
                return RedirectToAction(nameof(Pool), new { prefix, page });
            }
            return BadRequest();
        }
        public IActionResult RemovePrefix(string selectedPrefix, string prefix, int page)
        {
            if (ModelState.IsValid)
            {
                var prefixes = selectedPrefix.Split(',');
                repository.RemovePrefix( User.Identity.Name, prefixes);
                return RedirectToAction(nameof(Pool), new { prefix, page });
            }
            else
            {
                return BadRequest();
            }
        }

        public IActionResult AttachPrefix(string selectedPrefix, long neId, string prefix, int page)
        {
            if (ModelState.IsValid)
            {
                var prefixes = selectedPrefix.Split(',');
                repository.AttachNumberingPool(neId, User.Identity.Name, prefixes);
                return RedirectToAction(nameof(Pool), new { prefix, page });
            }
            else
            {
                return BadRequest();
            }
        }
    }
}

Sarona/Views/Report/FullSheet.cshtml
@model IEnumerable<FullPageRecord>
@using Sarona

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Full Page";
}



    <h3>Full Page</h3>

    <table class="table table-bordered">
        <tbody>
            @foreach (var row in Model.GroupBy(x => x.Row).OrderBy(x => x.Key))
            {
                <tr>
                    @foreach (var td in row)
                    {
                        <td bgcolor="@td.Color.ToHex()"><a asp-action="Pool" asp-controller="Numbering" asp-route-prefix="@td.Prefix" target="_blank" data-toggle="tooltip" data-placement="top" data-html="true" title="@Html.Raw(td.Description)">@td.Prefix </a></td>
                    }
                </tr>
            }
        </tbody>
    </table>

@section Scripts{
    <script>
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
        $(document).ready(function () {
            $('.table-responsive').do
        })
    </script>
}

Sarona/Views/Report/NE.cshtml
@model NetworkElement
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Network Element";
}

<form method="get" class="form-inline" asp-action="Ne">
    <label class="mr-2">Area</label>
    <select asp-items="@Html.GetEnumSelectList<Area>()" class="form-control mr-2" onchange="$('#attachNE').text('');PopulateExchange($(this).val(),'accessExchange');">
        <option value="" disabled selected>Please select an area!</option>
        
    </select>
    <label class="mr-2">Exchange</label>
    <select class="form-control mr-2" id="accessExchange" onchange="PopulateNE($(this).val(), '' ,'attachNE')"></select>
    <label class="mr-2">Network Element</label>
    <select required class="form-control mr-2" name="neId" id="attachNE"></select>
    <button type="submit" class="btn btn-primary">Search</button>
</form>



@if (Model is null)
{

}
else
{
    <h2 class="my-3">@Model.Name (@Model.Model - @Model.Manufacturer)</h2>
    <form id="getExcel" asp-action="NeExcel" asp-controller="Report" method="get">
        <i style="cursor:pointer" onclick="$('#getExcel').submit()" class="fas fa-file-excel fa-2x float-right"></i>
        <input type="hidden" name="neId" value="@Model.Id" />
    </form>
    <ul class="nav nav-tabs" id="tab">
        <li class="nav-item">
            <a class="nav-link active" id="links-tab" data-toggle="tab" href="#links">Links <span class="badge badge-secondary">@Model.LinksOnEnd1.Count()</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="numberings-tab" data-toggle="tab" href="#numberings">Numberings <span class="badge badge-secondary">@Model.NumberingPoolNetworkElements.Count()</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="remotes-tab" data-toggle="tab" href="#remotes">Remotes <span class="badge badge-secondary">@Model.NetworkElements.Where(x => x.NetworkType == NeType.Remote).Count()</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="accesses-tab" data-toggle="tab" href="#accesses">Accesses <span class="badge badge-secondary">@Model.NetworkElements.Where(x => x.NetworkType == NeType.Access).Count()</span></a>
        </li>
    </ul>
    <div class="tab-content" id="tabContent">
        <div class="tab-pane fade show active" id="links">
            <div class="table-responsive mt-3 pb-3">
                <table class="@Settings.TableClass" hidden style="width:100%" id="coreTable">
                    <thead>
                        <tr>
                            <td>Name</td>
                            <td>Exchange</td>
                            <td>Channels</td>
                            <td>[STM1,E1,Channels]</td>
                            <td>Direction</td>
                            <td>Type</td>
                            <td>Remark</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var link in Model.LinksOnEnd1)
                        {
                            <tr>
                                <td>@link.End2.Name</td>
                                <td>@link.End2.Exchange.Abb (@link.End2.Exchange.Name)</td>
                                <td>@link.Channels</td>
                                <td>@link.GetStm1E1()</td>
                                <td>@link.Direction</td>
                                <td>@link.Type</td>
                                <td>@link.Remark</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <div class="tab-pane fade" id="numberings">
            <div class="table-responsive mt-3 pb-3">
                <table class="@Settings.TableClass" hidden style="width:100% !important" id="numberingTable">
                    <thead>
                        <tr>
                            <th>Prefix</th>
                            <th>Min-Max</th>
                            <th>Charging</th>
                            <th>Type</th>
                            <th>Float</th>
                            <th>Remark</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var number in Model.NumberingPoolNetworkElements)
                        {
                            <tr>
                                <td>@number.Numbering.Prefix</td>
                                <td>@number.Numbering.Min-@number.Numbering.Max</td>
                                <td>@number.Numbering.ChargingCase</td>
                                <td>@number.Numbering.NumberType</td>
                                <td><span class="@(number.Numbering.IsFloat ? "fa fa-check":"fa fa-times")"></span></td>
                                <td>@number.Numbering.Remark</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>

        </div>
        <div class="tab-pane fade" id="remotes">
            <div class="table-responsive mt-3 pb-3">
                <table id="remoteTable" style="width:100%" hidden class="@Settings.TableClass my-3">
                    <thead>
                        <tr>
                            <td>Name</td>
                            <td>Exchange</td>
                            <td>Area</td>
                            <td>Type</td>
                            <td>Model</td>
                            <td>Manufacturer</td>
                            <td>Installed Capacity</td>
                            <td>Used Capacity</td>
                            <td>Numberings</td>
                            <td>Remark</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var remote in Model.NetworkElements.Where(x => x.NetworkType == NeType.Remote))
                        {
                            <tr>
                                <td>@remote.Name</td>
                                <td>@remote.Exchange.Abb (@remote.Exchange.Name)</td>
                                <td>@remote.Exchange.Area</td>
                                <td>@remote.Type</td>
                                <td>@remote.Model</td>
                                <td>@remote.Manufacturer</td>
                                <td>@remote.InstalledCapacity</td>
                                <td>@remote.UsedCapacity</td>
                                <td>@remote.GetNumberings()</td>
                                <td>@remote.Remark</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>

        </div>
        <div class="tab-pane fade" id="accesses">
            <div class="table-responsive mt-3 pb-3">
                <table id="accessTable" style="width:100%" hidden class="@Settings.TableClass my-3">
                    <thead>
                        <tr>
                            <td>Name</td>
                            <td>Exchange</td>
                            <td>Area</td>
                            <td>Type</td>
                            <td>Model</td>
                            <td>Manufacturer</td>
                            <td>Installed Capacity</td>
                            <td>Used Capacity</td>
                            <td>Numberings</td>
                            <td>Remark</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var remote in Model.NetworkElements.Where(x => x.NetworkType == NeType.Access))
                        {
                            <tr>
                                <td>@remote.Name</td>
                                <td>@remote.Exchange.Abb (@remote.Exchange.Name)</td>
                                <td>@remote.Exchange.Area</td>
                                <td>@remote.Type</td>
                                <td>@remote.Model</td>
                                <td>@remote.Manufacturer</td>
                                <td>@remote.InstalledCapacity</td>
                                <td>@remote.UsedCapacity</td>
                                <td>@remote.GetNumberings()</td>
                                <td>@remote.Remark</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>

        </div>
    </div>
}

@section Scripts{
    <script>
        $(document).ready(function () {
            $('#numberingTable').DataTable({
                pageLength: 50
            });
            $('#numberingTable').removeAttr("hidden");
        });

        $(document).ready(function () {
            $('#coreTable').DataTable({
                pageLength: 50
            });
            $('#coreTable').removeAttr("hidden");
        });

        $(document).ready(function () {
            $('#remoteTable').DataTable({
                pageLength: 50
            });
            $('#remoteTable').removeAttr('hidden');
        });

        $(document).ready(function () {
            $('#accessTable').DataTable({
                pageLength: 50
            });
            $('#accessTable').removeAttr('hidden');
        });

    </script>


}

Sarona/Views/Report/Numbering.cshtml
@model Sarona.ViewModels.NumberingSearchViewModel

@{
    ViewData["Title"] = "Numbering";
}

<h2>Numbering</h2>


<form method="get" id="searchForm" class="my-3" asp-action="numbering">
    <div class="row">
        <div class="col">
            <div class="form-group">
                <label asp-for="Search.Prefix"></label>
                <input class="form-control" asp-for="Search.Prefix" />
            </div>
            <div class="form-group">
                <label asp-for="Search.PrefixMode"></label>
                <select class="form-control" asp-for="Search.PrefixMode" asp-items="Html.GetEnumSelectList<QueryMode>()"></select>
            </div>

            <div class="form-group">
                <label asp-for="Search.Min"></label>
                <input class="form-control" asp-for="Search.Min" />
            </div>
            <div class="form-group">
                <label asp-for="Search.Max"></label>
                <input class="form-control" asp-for="Search.Max" />
            </div>
            <div class="form-group">
                <label asp-for="Search.SubscriberName"></label>
                <input class="form-control" asp-for="Search.SubscriberName" />
            </div>
            <div class="form-group">
                <label asp-for="Search.Abb"></label>
                <input class="form-control" asp-for="Search.Abb" />
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="Search.Areas"></label>
                <select multiple class="form-control" asp-for="Search.Areas" asp-items="@Html.GetEnumSelectList<Area>()"></select>
            </div>
            
            <div class="form-group">
                <label asp-for="Search.NumberTypes"></label>
                <select multiple class="form-control" asp-for="Search.NumberTypes" asp-items="new SelectList(Model.Miscs.Where(x=>x.Type == MiscType.NumberType).Select(x=>x.Name),Model.Miscs.Where(x=>x.Type == MiscType.NumberType).Select(x=>x.Name)) "></select>
            </div>
            <div class="form-group">
                <label asp-for="Search.RondTypes"></label>
                <select multiple class="form-control" asp-for="Search.RondTypes" asp-items="Html.GetEnumSelectList<GSB>() "></select>
            </div>

        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="Search.LinkTypes"></label>
                <select multiple class="form-control" asp-for="Search.LinkTypes" asp-items="@Html.GetEnumSelectList<LinkType>()"></select>
            </div>

            <div class="form-group">
                <label asp-for="Search.ChargingCases"></label>
                <select multiple class="form-control" asp-for="Search.ChargingCases" asp-items=" new SelectList(Model.Miscs.Where(x=>x.Type == MiscType.ChargingCase).Select(x=>x.Name),Model.Miscs.Where(x=>x.Type == MiscType.ChargingCase).Select(x=>x.Name)) "></select>
            </div>
            <div class="form-group">
                <label asp-for="Search.Directions"></label>
                <select multiple class="form-control" asp-for="Search.Directions" asp-items="new SelectList(Enum.GetNames(typeof(LinkDirection)),Enum.GetValues(typeof(LinkDirection))) "></select>
            </div>
            
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="Search.Statuses"></label>
                <select multiple class="form-control" asp-for="Search.Statuses" asp-items="new SelectList(Enum.GetNames(typeof(NumberingStatus)),Enum.GetValues(typeof(NumberingStatus))) "></select>
            </div>
            <div class="form-group">
                <label asp-for="Search.Owners"></label>
                <select multiple class="form-control" asp-for="Search.Owners" asp-items="new SelectList(Model.Miscs.Where(x=>x.Type == MiscType.Owner).Select(x=>x.Name),Model.Miscs.Where(x=>x.Type == MiscType.Owner).Select(x=>x.Name)) "></select>
            </div>
        </div>

    </div>
    <input type="hidden" name="page" id="page" value="1">
    <button type="submit" class="btn btn-primary">Search</button>
    <a class="btn btn-secondary" asp-action="numbering" asp-controller="report">Clear</a>
</form>
<form id="excelForm" asp-action="NumberingExcel" method="get">
    <i style="cursor:pointer" onclick="$('#excelForm').submit()" class="fas fa-file-excel fa-2x float-right"></i>
    <input type="hidden" asp-for="ExcelSearch.Abb" />
    @for (int i = 0; i < Model.ExcelSearch.ChargingCases?.Count(); i++)
    {
        <input type="hidden" asp-for="ExcelSearch.ChargingCases[i]" />
    }

    <input type="hidden" asp-for="ExcelSearch.Max" />
    <input type="hidden" asp-for="ExcelSearch.Min" />
    <input type="hidden" asp-for="ExcelSearch.Prefix" />
    <input type="hidden" asp-for="ExcelSearch.PrefixMode" />
    <input type="hidden" asp-for="ExcelSearch.SubscriberName" />
    @for (int i = 0; i < Model.ExcelSearch.Directions?.Count(); i++)
    {
        <input type="hidden" asp-for="ExcelSearch.Directions[i]" />
    }
    @for (int i = 0; i < Model.ExcelSearch.NumberTypes?.Count(); i++)
    {
        <input type="hidden" asp-for="ExcelSearch.NumberTypes[i]" />
    }
    @for (int i = 0; i < Model.ExcelSearch.Owners?.Count(); i++)
    {
        <input type="hidden" asp-for="ExcelSearch.Owners[i]" />
    }
    @for (int i = 0; i < Model.ExcelSearch.RondTypes?.Count(); i++)
    {
        <input type="hidden" asp-for="ExcelSearch.RondTypes[i]" />
    }
    @for (int i = 0; i < Model.ExcelSearch.Statuses?.Count(); i++)
    {
        <input type="hidden" asp-for="ExcelSearch.Statuses[i]" />
    }
    @for (int i = 0; i < Model.ExcelSearch.Areas?.Count(); i++)
    {
        <input type="hidden" asp-for="ExcelSearch.Areas[i]" />
    }
    @for (int i = 0; i < Model.ExcelSearch.LinkTypes?.Count(); i++)
    {
        <input type="hidden" asp-for="ExcelSearch.LinkTypes[i]" />
    }
    @for (int i = 0; i < Model.ExcelSearch.ChargingCases?.Count(); i++)
    {
        <input type="hidden" asp-for="ExcelSearch.ChargingCases[i]" />
    }

</form>

<div class="d-flex justify-content-center mb-3">
    <span class="mr-2">Page </span>
    <select class="mr-2" onchange="LoadPage(this);">
        @for (int i = 1; i < Model.PageInfo.TotalPages + 1; i++)
        {
            if (i == Model.PageInfo.CurrentPage)
            {
                @:<option selected value="@i">@i</option>
            }
            else
            {
                @:<option value="@i">@i</option>
            }
        }
    </select>
    <span> of @Model.PageInfo.TotalPages pages.</span>
</div>
<div class="table-responsive">
    <table class="mt-3 @Settings.TableClass">
        <thead>
            <tr>
                <th>Prefix</th>
                <th>Min-Max</th>
                <th>Min-Max (Sheet)</th>
                <th>Area</th>
                <th>Area (Sheet)</th>
                <th>Rond</th>
                <th>Number Type</th>
                <th>Subscriber</th>
                <th>Abbreviation</th>
                <th>Link Type</th>
                <th>Direction</th>
                <th>Float</th>
                <th>Keshvari</th>
                <th>Status</th>
                <th>Owner</th>
                <th>NE</th>
                <th>Charging</th>
                <th>Remark</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var number in Model.Results)
            {
                <tr>
                    <td>@number.Prefix</td>
                    <td>@number.Min-@number.Max</td>
                    <td>@number.SecondaryMin-@number.SecondaryMax</td>
                    <td>@number.Area</td>
                    <td>@number.SecondaryArea</td>
                    <td>@number.Rond</td>
                    <td>@number.NumberType</td>
                    <td>@($"{number.SubscriberName}")</td>
                    <td>@number.Abb</td>
                    <td>@(number.Link?.ToString() ?? "")</td>
                    <td>@(number.Direction?.ToString() ?? "")</td>
                    <td><span class="@(@number.IsFloat ? "fa fa-check":"fa fa-times")"></span></td>
                    <td><span class="@(@number.IsKeshvari ? "fa fa-check":"fa fa-times")"></span></td>
                    <td>@number.Status</td>
                    <td>@number.Owner</td>
                    <td>@number.GetNetworkElementNamesHtml()</td>
                    <td>@number.ChargingCase</td>
                    <td>@number.Remark</td>
                </tr>
            }
        </tbody>
    </table>
</div>

@section Scripts{
    <script>
        function LoadPage(select) {
            var selectedPage = $(select).find(":selected").text();
            $("#page").val(selectedPage);
            $("#searchForm").submit();

            
        }
    </script>
}

Sarona/Views/Report/RedFolder.cshtml
@model RedFolderViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Red Folder";
}


    <h3>Red Folder</h3>
    <form method="get" asp-action="RedFolder">
        <div class="form-group">
            <label for="abb">Subscriber Abbreviation</label>
            <input class="form-control" style="width:300px" name="abb" value="@Model.Abb" />
        </div>
        <div class="form-group">
            <label for="code">Subscriber Code</label>
            <input class="form-control" style="width:300px" name="code" value="@Model.Code" />
        </div>
        <div class="form-group">
            <label asp-for="Mode">Query Mode</label>
            <select class="form-control" asp-for="Mode" style="width:300px" asp-items="new SelectList(Enum.GetValues(typeof(QueryMode)),Enum.GetNames(typeof(QueryMode)))"></select>
                    </div>
        <button class="btn btn-primary" type="submit">Search</button>
    </form>
    <form id="getExcel" asp-action="RedFolderExcel" asp-controller="Report" method="get">
        <i style="cursor:pointer" onclick="$('#getExcel').submit()" class="fas fa-file-excel fa-2x float-right"></i>
        <input type="hidden" name="abb" value="@Model.Abb" />
        <input type="hidden" name="code" value="@Model.Code" />
        <input type="hidden" name="mode" value="@Model.Mode" />
    </form>
    <div class="d-flex justify-content-center mb-3">
        <span class="mr-2">Page </span>
        <select class="mr-2" onchange="LoadPage(this);">
            @for (int i = 1; i < Model.PagingInfo.TotalPages + 1; i++)
            {
                if (i == Model.PagingInfo.CurrentPage)
                {
                    @:<option selected value="@i">@i</option>
                }
                else
                {
                    @:<option value="@i">@i</option>
                }
            }
        </select>
        <span> of @Model.PagingInfo.TotalPages pages.</span>
    </div>

    <div class="table-responsive">
        <table class="@Settings.TableClass">
            <thead>
                <tr>
                    <th>Subscriber Abbreviation</th>
                    <th>Subscriber Code</th>
                    <th>Switch Abbreviation</th>
                    <th>Switch Code</th>
                    <th>Link Type</th>
                    <th>Channels</th>
                    <th>Remark</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var record in Model.Records)
                {
                    <tr>
                        <td>@record.SubscriberAbb</td>
                        <td>@record.SubscriberCode</td>
                        <td>@record.SwitchAbb</td>
                        <td>@record.SwitchCode</td>
                        <td>@record.LinkType</td>
                        <td>@record.Channels</td>
                        <td>@record.Remark</td>
                    </tr>
                }

            </tbody>
        </table>
    </div>

    <div class="d-flex justify-content-center mb-3">
        <span class="mr-2">Page </span>
        <select class="mr-2" onchange="LoadPage(this);">
            @for (int i = 1; i < Model.PagingInfo.TotalPages + 1; i++)
            {
                if (i == Model.PagingInfo.CurrentPage)
                {
                    @:<option selected value="@i">@i</option>
                }
                else
                {
                    @:<option value="@i">@i</option>
                }
            }
        </select>
        <span> of @Model.PagingInfo.TotalPages pages.</span>
    </div>

@section Scripts{
    <script>
        function LoadPage(select) {
            var selectedPage = $(select).find(":selected").text();
            location.assign("/report/redfolder?abb=@Model.Abb&code=@Model.Code&page="+selectedPage)
        }
    </script>
}